version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  go: circleci/go@0.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - go/mod-download
      - run:
          name: Run Tests
          command: go test -v -coverprofile=coverage.txt -covermode=atomic ./pkg/actor | go-junit-report > ${TEST_RESULTS}/result.xml
      - store_test_results:
          path: /tmp/test-results
      - codecov/upload:
          file: coverage.txt