version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  go: circle/go@0.2.0
jobs:
  build:
    docker:
      - image: circleci/go:1.11
    steps:
      - checkout
      - go/mod-download
      - go/test
      - store_test_results:
          path: test-results
      - codecov/upload:
          file: coverage/cobertura-coverage.xml